# Generated by Django 2.2.1 on 2019-05-09 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('talle', models.CharField(choices=[('S', 'Pequeña'), ('M', 'Mediano'), ('L', 'Largo'), ('XL', 'Extra largo')], max_length=1)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Queremos que guardes el titulo de la pregunta', max_length=200)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'ordering': ['-creacion'],
            },
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Queremos que guardes el titulo de la opcion', max_length=200)),
                ('votos', models.IntegerField(help_text='Votos de la opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Pregunta')),
            ],
            options={
                'verbose_name': 'opcion',
                'verbose_name_plural': 'opciones',
                'ordering': ['votos'],
            },
        ),
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Talle')),
            ],
            options={
                'verbose_name_plural': 'autoridades',
            },
        ),
    ]
